bump Golang from 1.23 to 1.25

diff --git a/docker/blockchain/Dockerfile b/docker/blockchain/Dockerfile
--- a/docker/blockchain/Dockerfile
+++ b/docker/blockchain/Dockerfile
@@ -1,4 +1,4 @@
-FROM golang:1.23-bullseye AS build
+FROM golang:1.25-bookworm AS build
 ARG VERSION
 
 WORKDIR /go/src/github.com/provenance-io/provenance
@@ -24,29 +24,29 @@ COPY Makefile sims.mk ./
 ENV VERSION=$VERSION
 RUN ARCH=$(uname -m) && \
     if [ "$ARCH" != "x86_64" ] && [ "$ARCH" != "aarch64" ]; then \
-        echo "Unsupported architecture (required: x86_64 or aarch64): $ARCH"; \
-        exit 1; \
+    echo "Unsupported architecture (required: x86_64 or aarch64): $ARCH"; \
+    exit 1; \
     fi && \
     echo "Building and installing provenance for Arch: $ARCH"; \
     make VERSION=${VERSION} install
 
 ###
-FROM debian:bullseye-slim AS run
+FROM debian:bookworm-slim AS run
 ENV LD_LIBRARY_PATH="/usr/local/lib"
 RUN apt-get update && \
     apt-get upgrade -y && \
     apt-get install -y curl jq libleveldb-dev && \
     apt-get clean && \
     rm -rf /var/lib/apt/lists/
-    
+
 
 COPY --from=build /go/src/github.com/provenance-io/provenance/vendor/github.com/CosmWasm/wasmvm/v2/internal/api/libwasmvm.*.so /tmp
 COPY --from=build /go/bin/provenanced /usr/bin/provenanced
 
 RUN ARCH=$(uname -m) && \
     if [ "$ARCH" != "x86_64" ] && [ "$ARCH" != "aarch64" ]; then \
-        echo "Unsupported architecture (required: x86_64 or aarch64): $ARCH"; \
-        exit 1; \
+    echo "Unsupported architecture (required: x86_64 or aarch64): $ARCH"; \
+    exit 1; \
     fi && \
     cp "/tmp/libwasmvm.$ARCH.so" /usr/local/lib/. && \
     rm /tmp/libwasmvm.*.so
@@ -56,4 +56,3 @@ WORKDIR /home/provenance
 
 EXPOSE 1317 9090 26656 26657
 CMD ["/usr/bin/provenanced"]
-
