feat(ghrc-registry): include missing legacy_protos path to fix Docker build

diff --git a/docker/blockchain/Dockerfile b/docker/blockchain/Dockerfile
--- a/docker/blockchain/Dockerfile
+++ b/docker/blockchain/Dockerfile
@@ -17,6 +17,7 @@ COPY vendor/ ./vendor/
 COPY testutil/ ./testutil/
 COPY .git/ ./.git/
 COPY contrib/ ./contrib/
+COPY legacy_protos/ ./legacy_protos/
 COPY Makefile sims.mk ./
 
 
@@ -24,8 +25,8 @@ COPY Makefile sims.mk ./
 ENV VERSION=$VERSION
 RUN ARCH=$(uname -m) && \
     if [ "$ARCH" != "x86_64" ] && [ "$ARCH" != "aarch64" ]; then \
-        echo "Unsupported architecture (required: x86_64 or aarch64): $ARCH"; \
-        exit 1; \
+    echo "Unsupported architecture (required: x86_64 or aarch64): $ARCH"; \
+    exit 1; \
     fi && \
     echo "Building and installing provenance for Arch: $ARCH"; \
     make VERSION=${VERSION} install
@@ -38,15 +39,15 @@ RUN apt-get update && \
     apt-get install -y curl jq libleveldb-dev && \
     apt-get clean && \
     rm -rf /var/lib/apt/lists/
-    
+
 
 COPY --from=build /go/src/github.com/provenance-io/provenance/vendor/github.com/CosmWasm/wasmvm/v2/internal/api/libwasmvm.*.so /tmp
 COPY --from=build /go/bin/provenanced /usr/bin/provenanced
 
 RUN ARCH=$(uname -m) && \
     if [ "$ARCH" != "x86_64" ] && [ "$ARCH" != "aarch64" ]; then \
-        echo "Unsupported architecture (required: x86_64 or aarch64): $ARCH"; \
-        exit 1; \
+    echo "Unsupported architecture (required: x86_64 or aarch64): $ARCH"; \
+    exit 1; \
     fi && \
     cp "/tmp/libwasmvm.$ARCH.so" /usr/local/lib/. && \
     rm /tmp/libwasmvm.*.so
