Combine all the sim tests and db types into a single matrix github action.

diff --git a/.github/workflows/sims.yml b/.github/workflows/sims.yml
--- a/.github/workflows/sims.yml
+++ b/.github/workflows/sims.yml
@@ -88,6 +88,7 @@ jobs:
         run: export GO111MODULE="on" && go get github.com/cosmos/tools/cmd/runsim@v1.0.0
 
   build-provenanced:
+    # This is here so that, if it fails to build, you get one failure instead of 16, and saves a little github action effort.
     runs-on: ubuntu-latest
     needs: [setup, build-dependencies]
     if: needs.setup.outputs.should-run
@@ -121,146 +122,7 @@ jobs:
         run: |
           provenanced version --long
 
-  simple-goleveldb:
-    runs-on: ubuntu-latest
-    needs: [setup, build-dependencies, build-provenanced]
-    if: needs.setup.outputs.should-run
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/cache@v3
-        with:
-          key: ${{ needs.setup.outputs.cache-key }}
-          path: ${{ needs.setup.outputs.cache-path }}
-      - uses: actions/setup-go@v3
-        with:
-          go-version: 1.17
-      - name: Display go version
-        run: go version
-      - name: test-sim-simple goleveldb
-        run: |
-          ec=0
-          make DB_BACKEND=goleveldb test-sim-simple || ec="$?"
-          [[ "$ec" -eq '0' ]] || tar -czvf test-sim-${{ github.job }}-goleveldb-logs.tar.gz /tmp/sim-logs-*
-          exit "$ec"
-      - uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: ${{ github.job }}-goleveldb-logs
-          path: test-sim-${{ github.job }}-goleveldb-logs.tar.gz
-
-  simple-cleveldb:
-    runs-on: ubuntu-latest
-    needs: [setup, build-dependencies, build-provenanced]
-    if: needs.setup.outputs.should-run
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/cache@v3
-        with:
-          key: ${{ needs.setup.outputs.cache-key }}
-          path: ${{ needs.setup.outputs.cache-path }}
-      - name: Install cleveldb
-        env:
-          DEBIAN_FRONTEND: noninteractive
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y libleveldb-dev
-          sudo apt-get install -y libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
-      - uses: actions/setup-go@v3
-        with:
-          go-version: 1.17
-      - name: Display go version
-        run: go version
-      - name: test-sim-simple cleveldb
-        run: |
-          ec=0
-          make DB_BACKEND=cleveldb test-sim-simple || ec="$?"
-          [[ "$ec" -eq '0' ]] || tar -czvf test-sim-${{ github.job }}-cleveldb-logs.tar.gz /tmp/sim-logs-*
-          exit "$ec"
-      - uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: ${{ github.job }}-cleveldb-logs
-          path: test-sim-${{ github.job }}-cleveldb-logs.tar.gz
-
-  simple-rocksdb:
-    runs-on: ubuntu-latest
-    needs: [setup, build-dependencies, build-provenanced]
-    if: needs.setup.outputs.should-run
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/cache@v3
-        with:
-          key: ${{ needs.setup.outputs.cache-key }}
-          path: ${{ needs.setup.outputs.cache-path }}
-      - name: Install rocksdb
-        run: |
-          export ROCKSDB_SUDO='true'
-          export ROCKSDB_DO_CLEANUP='false'
-          export ROCKSDB_DO_BUILD='false'
-          make rocksdb
-      - uses: actions/setup-go@v3
-        with:
-          go-version: 1.17
-      - name: Display go version
-        run: go version
-      - name: test-sim-simple rocksdb
-        run: |
-          ec=0
-          make DB_BACKEND=rocksdb test-sim-simple || ec="$?"
-          [[ "$ec" -eq '0' ]] || tar -czvf test-sim-${{ github.job }}-rocksdb-logs.tar.gz /tmp/sim-logs-*
-          exit "$ec"
-      - uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: ${{ github.job }}-rocksdb-logs
-          path: test-sim-${{ github.job }}-rocksdb-logs.tar.gz
-
-  simple-badgerdb:
-    runs-on: ubuntu-latest
-    needs: [setup, build-dependencies, build-provenanced]
-    if: needs.setup.outputs.should-run
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/cache@v3
-        with:
-          key: ${{ needs.setup.outputs.cache-key }}
-          path: ${{ needs.setup.outputs.cache-path }}
-      - uses: actions/setup-go@v3
-        with:
-          go-version: 1.17
-      - name: Display go version
-        run: go version
-      - name: test-sim-simple badgerdb
-        run: |
-          ec=0
-          make DB_BACKEND=badgerdb test-sim-simple || ec="$?"
-          [[ "$ec" -eq '0' ]] || tar -czvf test-sim-${{ github.job }}-badgerdb-logs.tar.gz /tmp/sim-logs-*
-          exit "$ec"
-      - uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: ${{ github.job }}-badgerdb-logs
-          path: test-sim-${{ github.job }}-badgerdb-logs.tar.gz
-
-  nondeterminism:
-    runs-on: ubuntu-latest
-    needs: [setup, build-dependencies, build-provenanced]
-    if: needs.setup.outputs.should-run
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/cache@v3
-        with:
-          key: ${{ needs.setup.outputs.cache-key }}
-          path: ${{ needs.setup.outputs.cache-path }}
-      - uses: actions/setup-go@v3
-        with:
-          go-version: 1.17
-      - name: Display go version
-        run: go version
-      - name: test-sim-nondeterminism
-        run: make test-sim-nondeterminism
-
-  import-export:
+  run-sims:
     runs-on: ubuntu-latest
     needs: [setup, build-dependencies, build-provenanced]
     if: needs.setup.outputs.should-run
@@ -268,6 +130,7 @@ jobs:
       fail-fast: false
       matrix:
         db-backend: ["goleveldb", "cleveldb", "rocksdb", "badgerdb"]
+        test: ["test-sim-simple", "test-sim-nondeterminism", "test-sim-import-export", "test-sim-multi-seed-short"]
     steps:
       - uses: actions/checkout@v3
       - uses: actions/cache@v3
@@ -294,32 +157,14 @@ jobs:
           go-version: 1.17
       - name: Display go version
         run: go version
-      - name: test-sim-import-export goleveldb
+      - name: run sim
         run: |
           ec=0
-          make DB_BACKEND=${{ matrix.db-backend }} test-sim-import-export || ec="$?"
-          [[ "$ec" -eq '0' ]] || tar -czvf test-sim-${{ github.job }}-${{ matrix.db-backend }}-logs.tar.gz /tmp/sim-logs-*
+          make DB_BACKEND=${{ matrix.db-backend }} ${{ matrix.test }} || ec="$?"
+          [[ "$ec" -eq '0' ]] || tar -czvf ${{ matrix.test }}-${{ matrix.db-backend }}-logs.tar.gz /tmp/sim-logs-*
           exit "$ec"
       - uses: actions/upload-artifact@v3
         if: failure()
         with:
-          name: ${{ github.job }}-${{ matrix.db-backend }}-logs
-          path: test-sim-${{ github.job }}-${{ matrix.db-backend }}-logs.tar.gz
-
-  multi-seed-short:
-    runs-on: ubuntu-latest
-    needs: [setup, build-dependencies, build-provenanced]
-    if: needs.setup.outputs.should-run
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/cache@v3
-        with:
-          key: ${{ needs.setup.outputs.cache-key }}
-          path: ${{ needs.setup.outputs.cache-path }}
-      - uses: actions/setup-go@v3
-        with:
-          go-version: 1.17
-      - name: Display go version
-        run: go version
-      - name: test-sim-multi-seed-short
-        run: make test-sim-multi-seed-short
+          name: ${{ matrix.test }}-${{ matrix.db-backend }}-logs
+          path: ${{ matrix.test }}-${{ matrix.db-backend }}-logs.tar.gz
